# Generated by Django 2.2.14 on 2021-12-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211226_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
